obj-y = hdmi-priv.o hdmi-preset.o nxp-edid.o nxp-hdcp.o nxp-hdmiphy.o nxp-hdmi-context.o

EXTRA_CFLAGS += -Idrivers/media/video/nexell
EXTRA_CFLAGS += -I$(srctree)/arch/arm/mach-s5p6818/prototype/base -I$(srctree)/arch/arm/mach-s5p6818/prototype/module
