obj-$(CONFIG_VIDEO_NXP_CAPTURE) += nxp-capture.o nxp-vin-clipper.o
obj-$(CONFIG_NXP_CAPTURE_DECIMATOR) += nxp-decimator.o
obj-$(CONFIG_NXP_CAPTURE_MIPI_CSI)  += nxp-csi.o

EXTRA_CFLAGS += -Idrivers/media/video/nexell
