#ifndef _VIDEODEV2_NXP_MEDIA_H
#define _VIDEODEV2_NXP_MEDIA_H

/*
 * C O N T R O L S
 */
#define V4L2_CID_NXP_BASE                V4L2_CTRL_CLASS_USER

/* HDMI : 1 ~ 20 */
#define V4L2_CID_HDMI_HPD_STATUS         (V4L2_CID_NXP_BASE + 1)
#define V4L2_CID_HDMI_SET_DVI_MODE       (V4L2_CID_NXP_BASE + 2)
#define V4L2_CID_HDMI_GET_DVI_MODE       (V4L2_CID_NXP_BASE + 3)
#define V4L2_CID_HDMI_SET_ASPECT_RATIO   (V4L2_CID_NXP_BASE + 4)
#define V4L2_CID_HDMI_MAX_AUDIO_CHANNELS (V4L2_CID_NXP_BASE + 5)
#define V4L2_CID_HDMI_ENABLE_HDMI_AUDIO  (V4L2_CID_NXP_BASE + 6)
#define V4L2_CID_HDMI_SET_NUM_CHANNELS   (V4L2_CID_NXP_BASE + 7)
#define V4L2_CID_HDMI_SET_COLOR_RANGE    (V4L2_CID_NXP_BASE + 8)
#define V4L2_CID_HDMI_ON_OFF             (V4L2_CID_NXP_BASE + 9)

/* MLC : 21 ~ 60 */
/* video : 21 ~ 40 */
#define V4L2_CID_MLC_VID_PRIORITY    (V4L2_CID_NXP_BASE + 21)
#define V4L2_CID_MLC_VID_COLORKEY    (V4L2_CID_NXP_BASE + 22)
#define V4L2_CID_MLC_VID_ALPHA       (V4L2_CID_NXP_BASE + 23)
#define V4L2_CID_MLC_VID_HFILTER     (V4L2_CID_NXP_BASE + 24)
#define V4L2_CID_MLC_VID_VFILTER     (V4L2_CID_NXP_BASE + 25)
/* rgb : 41 ~ 60 */
#define V4L2_CID_MLC_RGB_ALPHA       (V4L2_CID_NXP_BASE + 41)
#define V4L2_CID_MLC_RGB_TRANSCOLOR  (V4L2_CID_NXP_BASE + 43)
#define V4L2_CID_MLC_RGB_INVERTCOLOR (V4L2_CID_NXP_BASE + 45)
#define V4L2_CID_MLC_RGB_BACKCOLOR   (V4L2_CID_NXP_BASE + 47)
#define V4L2_CID_MLC_RGB_INVALIDZONE (V4L2_CID_NXP_BASE + 50)

#endif
