/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from NEXELL Limited
 * (C) COPYRIGHT 2007-2013 NEXELL Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from NEXELL Limited.
 */

#ifndef _VR_UTGARD_COUNTERS_H_
#define _VR_UTGARD_COUNTERS_H_

typedef struct {
	void *unused;
} vr_cinstr_counter_info;

typedef enum {
	VR_CINSTR_COUNTER_SOURCE_EGL      =     0,
	VR_CINSTR_COUNTER_SOURCE_OPENGLES =  1000,
	VR_CINSTR_COUNTER_SOURCE_OPENVG   =  2000,
	VR_CINSTR_COUNTER_SOURCE_GP       =  3000,
	VR_CINSTR_COUNTER_SOURCE_PP       =  4000,
} cinstr_counter_source;

#define VR_CINSTR_EGL_FIRST_COUNTER VR_CINSTR_COUNTER_SOURCE_EGL
#define VR_CINSTR_EGL_LAST_COUNTER (VR_CINSTR_COUNTER_SOURCE_EGL + 999)

#define VR_CINSTR_GLES_FIRST_COUNTER VR_CINSTR_COUNTER_SOURCE_OPENGLES
#define VR_CINSTR_GLES_LAST_COUNTER (VR_CINSTR_COUNTER_SOURCE_OPENGLES + 999)

#define VR_CINSTR_VG_FIRST_COUNTER VR_CINSTR_COUNTER_SOURCE_OPENVG
#define VR_CINSTR_VG_LAST_COUNTER (VR_CINSTR_COUNTER_SOURCE_OPENVG + 999)

#define VR_CINSTR_GP_FIRST_COUNTER VR_CINSTR_COUNTER_SOURCE_GP
#define VR_CINSTR_GP_LAST_COUNTER (VR_CINSTR_COUNTER_SOURCE_GP + 999)

#define VR_CINSTR_PP_FIRST_COUNTER VR_CINSTR_COUNTER_SOURCE_PP
#define VR_CINSTR_PP_LAST_COUNTER (VR_CINSTR_COUNTER_SOURCE_PP + 999)


typedef enum {
	/* EGL counters */

	VR_CINSTR_EGL_BLIT_TIME                                            = VR_CINSTR_COUNTER_SOURCE_EGL + 0,

	/* Last counter in the EGL set */
	VR_CINSTR_EGL_MAX_COUNTER                                           = VR_CINSTR_COUNTER_SOURCE_EGL + 1,

	/* GLES counters */

	VR_CINSTR_GLES_DRAW_ELEMENTS_CALLS                                 = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 0,
	VR_CINSTR_GLES_DRAW_ELEMENTS_NUM_INDICES                           = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 1,
	VR_CINSTR_GLES_DRAW_ELEMENTS_NUM_TRANSFORMED                       = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 2,
	VR_CINSTR_GLES_DRAW_ARRAYS_CALLS                                   = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 3,
	VR_CINSTR_GLES_DRAW_ARRAYS_NUM_TRANSFORMED                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 4,
	VR_CINSTR_GLES_DRAW_POINTS                                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 5,
	VR_CINSTR_GLES_DRAW_LINES                                          = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 6,
	VR_CINSTR_GLES_DRAW_LINE_LOOP                                      = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 7,
	VR_CINSTR_GLES_DRAW_LINE_STRIP                                     = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 8,
	VR_CINSTR_GLES_DRAW_TRIANGLES                                      = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 9,
	VR_CINSTR_GLES_DRAW_TRIANGLE_STRIP                                 = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 10,
	VR_CINSTR_GLES_DRAW_TRIANGLE_FAN                                   = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 11,
	VR_CINSTR_GLES_NON_VBO_DATA_COPY_TIME                              = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 12,
	VR_CINSTR_GLES_UNIFORM_BYTES_COPIED_TO_VR                        = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 13,
	VR_CINSTR_GLES_UPLOAD_TEXTURE_TIME                                 = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 14,
	VR_CINSTR_GLES_UPLOAD_VBO_TIME                                     = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 15,
	VR_CINSTR_GLES_NUM_FLUSHES                                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 16,
	VR_CINSTR_GLES_NUM_VSHADERS_GENERATED                              = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 17,
	VR_CINSTR_GLES_NUM_FSHADERS_GENERATED                              = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 18,
	VR_CINSTR_GLES_VSHADER_GEN_TIME                                    = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 19,
	VR_CINSTR_GLES_FSHADER_GEN_TIME                                    = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 20,
	VR_CINSTR_GLES_INPUT_TRIANGLES                                     = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 21,
	VR_CINSTR_GLES_VXCACHE_HIT                                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 22,
	VR_CINSTR_GLES_VXCACHE_MISS                                        = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 23,
	VR_CINSTR_GLES_VXCACHE_COLLISION                                   = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 24,
	VR_CINSTR_GLES_CULLED_TRIANGLES                                    = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 25,
	VR_CINSTR_GLES_CULLED_LINES                                        = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 26,
	VR_CINSTR_GLES_BACKFACE_TRIANGLES                                  = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 27,
	VR_CINSTR_GLES_GBCLIP_TRIANGLES                                    = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 28,
	VR_CINSTR_GLES_GBCLIP_LINES                                        = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 29,
	VR_CINSTR_GLES_TRIANGLES_DRAWN                                     = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 30,
	VR_CINSTR_GLES_DRAWCALL_TIME                                       = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 31,
	VR_CINSTR_GLES_TRIANGLES_COUNT                                     = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 32,
	VR_CINSTR_GLES_INDEPENDENT_TRIANGLES_COUNT                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 33,
	VR_CINSTR_GLES_STRIP_TRIANGLES_COUNT                               = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 34,
	VR_CINSTR_GLES_FAN_TRIANGLES_COUNT                                 = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 35,
	VR_CINSTR_GLES_LINES_COUNT                                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 36,
	VR_CINSTR_GLES_INDEPENDENT_LINES_COUNT                             = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 37,
	VR_CINSTR_GLES_STRIP_LINES_COUNT                                   = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 38,
	VR_CINSTR_GLES_LOOP_LINES_COUNT                                    = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 39,
	VR_CINSTR_GLES_POINTS_COUNT                                        = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 40,

	/* Last counter in the GLES set */
	VR_CINSTR_GLES_MAX_COUNTER                                         = VR_CINSTR_COUNTER_SOURCE_OPENGLES + 41,

	/* OpenVG counters */

	VR_CINSTR_VG_MASK_COUNTER                                          = VR_CINSTR_COUNTER_SOURCE_OPENVG + 0,
	VR_CINSTR_VG_CLEAR_COUNTER                                         = VR_CINSTR_COUNTER_SOURCE_OPENVG + 1,
	VR_CINSTR_VG_APPEND_PATH_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 2,
	VR_CINSTR_VG_APPEND_PATH_DATA_COUNTER                              = VR_CINSTR_COUNTER_SOURCE_OPENVG + 3,
	VR_CINSTR_VG_MODIFY_PATH_COORDS_COUNTER                            = VR_CINSTR_COUNTER_SOURCE_OPENVG + 4,
	VR_CINSTR_VG_TRANSFORM_PATH_COUNTER                                = VR_CINSTR_COUNTER_SOURCE_OPENVG + 5,
	VR_CINSTR_VG_INTERPOLATE_PATH_COUNTER                              = VR_CINSTR_COUNTER_SOURCE_OPENVG + 6,
	VR_CINSTR_VG_PATH_LENGTH_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 7,
	VR_CINSTR_VG_POINT_ALONG_PATH_COUNTER                              = VR_CINSTR_COUNTER_SOURCE_OPENVG + 8,
	VR_CINSTR_VG_PATH_BOUNDS_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 9,
	VR_CINSTR_VG_PATH_TRANSFORMED_BOUNDS_COUNTER                       = VR_CINSTR_COUNTER_SOURCE_OPENVG + 10,
	VR_CINSTR_VG_DRAW_PATH_COUNTER                                     = VR_CINSTR_COUNTER_SOURCE_OPENVG + 11,
	VR_CINSTR_VG_CLEAR_IMAGE_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 12,
	VR_CINSTR_VG_IMAGE_SUB_DATA_COUNTER                                = VR_CINSTR_COUNTER_SOURCE_OPENVG + 13,
	VR_CINSTR_VG_GET_IMAGE_SUB_DATA_COUNTER                            = VR_CINSTR_COUNTER_SOURCE_OPENVG + 14,
	VR_CINSTR_VG_COPY_IMAGE_COUNTER                                    = VR_CINSTR_COUNTER_SOURCE_OPENVG + 15,
	VR_CINSTR_VG_DRAW_IMAGE_COUNTER                                    = VR_CINSTR_COUNTER_SOURCE_OPENVG + 16,
	VR_CINSTR_VG_SET_PIXELS_COUNTER                                    = VR_CINSTR_COUNTER_SOURCE_OPENVG + 17,
	VR_CINSTR_VG_WRITE_PIXELS_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 18,
	VR_CINSTR_VG_GET_PIXELS_COUNTER                                    = VR_CINSTR_COUNTER_SOURCE_OPENVG + 19,
	VR_CINSTR_VG_READ_PIXELS_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 20,
	VR_CINSTR_VG_COPY_PIXELS_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 21,
	VR_CINSTR_VG_COLOR_MATRIX_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 22,
	VR_CINSTR_VG_CONVOLVE_COUNTER                                      = VR_CINSTR_COUNTER_SOURCE_OPENVG + 23,
	VR_CINSTR_VG_SEPARABLE_CONVOLVE_COUNTER                            = VR_CINSTR_COUNTER_SOURCE_OPENVG + 24,
	VR_CINSTR_VG_GAUSSIAN_BLUR_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 25,
	VR_CINSTR_VG_LOOKUP_COUNTER                                        = VR_CINSTR_COUNTER_SOURCE_OPENVG + 26,
	VR_CINSTR_VG_LOOKUP_SINGLE_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 27,
	VR_CINSTR_VG_CONTEXT_CREATE_COUNTER                                = VR_CINSTR_COUNTER_SOURCE_OPENVG + 28,
	VR_CINSTR_VG_STROKED_CUBICS_COUNTER                                = VR_CINSTR_COUNTER_SOURCE_OPENVG + 29,
	VR_CINSTR_VG_STROKED_QUADS_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 30,
	VR_CINSTR_VG_STROKED_ARCS_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 31,
	VR_CINSTR_VG_STROKED_LINES_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 32,
	VR_CINSTR_VG_FILLED_CUBICS_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 33,
	VR_CINSTR_VG_FILLED_QUADS_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 34,
	VR_CINSTR_VG_FILLED_ARCS_COUNTER                                   = VR_CINSTR_COUNTER_SOURCE_OPENVG + 35,
	VR_CINSTR_VG_FILLED_LINES_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 36,
	VR_CINSTR_VG_DRAW_PATH_CALLS_COUNTER                               = VR_CINSTR_COUNTER_SOURCE_OPENVG + 37,
	VR_CINSTR_VG_TRIANGLES_COUNTER                                     = VR_CINSTR_COUNTER_SOURCE_OPENVG + 38,
	VR_CINSTR_VG_VERTICES_COUNTER                                      = VR_CINSTR_COUNTER_SOURCE_OPENVG + 39,
	VR_CINSTR_VG_INDICES_COUNTER                                       = VR_CINSTR_COUNTER_SOURCE_OPENVG + 40,
	VR_CINSTR_VG_FILLED_PATHS_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 41,
	VR_CINSTR_VG_STROKED_PATHS_COUNTER                                 = VR_CINSTR_COUNTER_SOURCE_OPENVG + 42,
	VR_CINSTR_VG_FILL_EXTRACT_COUNTER                                  = VR_CINSTR_COUNTER_SOURCE_OPENVG + 43,
	VR_CINSTR_VG_DRAW_FILLED_PATH_COUNTER                              = VR_CINSTR_COUNTER_SOURCE_OPENVG + 44,
	VR_CINSTR_VG_STROKE_EXTRACT_COUNTER                                = VR_CINSTR_COUNTER_SOURCE_OPENVG + 45,
	VR_CINSTR_VG_DRAW_STROKED_PATH_COUNTER                             = VR_CINSTR_COUNTER_SOURCE_OPENVG + 46,
	VR_CINSTR_VG_DRAW_PAINT_COUNTER                                    = VR_CINSTR_COUNTER_SOURCE_OPENVG + 47,
	VR_CINSTR_VG_DATA_STRUCTURES_COUNTER                               = VR_CINSTR_COUNTER_SOURCE_OPENVG + 48,
	VR_CINSTR_VG_MEM_PATH_COUNTER                                      = VR_CINSTR_COUNTER_SOURCE_OPENVG + 49,
	VR_CINSTR_VG_RSW_COUNTER                                           = VR_CINSTR_COUNTER_SOURCE_OPENVG + 50,

	/* Last counter in the VG set */
	VR_CINSTR_VG_MAX_COUNTER                                           = VR_CINSTR_COUNTER_SOURCE_OPENVG + 51,

	/* Vr GP counters */

	VR_CINSTR_GP_DEPRECATED_0                                          = VR_CINSTR_COUNTER_SOURCE_GP + 0,
	VR_CINSTR_GP_ACTIVE_CYCLES_GP                                      = VR_CINSTR_COUNTER_SOURCE_GP + 1,
	VR_CINSTR_GP_ACTIVE_CYCLES_VERTEX_SHADER                           = VR_CINSTR_COUNTER_SOURCE_GP + 2,
	VR_CINSTR_GP_ACTIVE_CYCLES_VERTEX_STORER                           = VR_CINSTR_COUNTER_SOURCE_GP + 3,
	VR_CINSTR_GP_ACTIVE_CYCLES_VERTEX_LOADER                           = VR_CINSTR_COUNTER_SOURCE_GP + 4,
	VR_CINSTR_GP_CYCLES_VERTEX_LOADER_WAITING_FOR_VERTEX_SHADER        = VR_CINSTR_COUNTER_SOURCE_GP + 5,
	VR_CINSTR_GP_NUMBER_OF_WORDS_READ                                  = VR_CINSTR_COUNTER_SOURCE_GP + 6,
	VR_CINSTR_GP_NUMBER_OF_WORDS_WRITTEN                               = VR_CINSTR_COUNTER_SOURCE_GP + 7,
	VR_CINSTR_GP_NUMBER_OF_READ_BURSTS                                 = VR_CINSTR_COUNTER_SOURCE_GP + 8,
	VR_CINSTR_GP_NUMBER_OF_WRITE_BURSTS                                = VR_CINSTR_COUNTER_SOURCE_GP + 9,
	VR_CINSTR_GP_NUMBER_OF_VERTICES_PROCESSED                          = VR_CINSTR_COUNTER_SOURCE_GP + 10,
	VR_CINSTR_GP_NUMBER_OF_VERTICES_FETCHED                            = VR_CINSTR_COUNTER_SOURCE_GP + 11,
	VR_CINSTR_GP_NUMBER_OF_PRIMITIVES_FETCHED                          = VR_CINSTR_COUNTER_SOURCE_GP + 12,
	VR_CINSTR_GP_RESERVED_13                                           = VR_CINSTR_COUNTER_SOURCE_GP + 13,
	VR_CINSTR_GP_NUMBER_OF_BACKFACE_CULLINGS_DONE                      = VR_CINSTR_COUNTER_SOURCE_GP + 14,
	VR_CINSTR_GP_NUMBER_OF_COMMANDS_WRITTEN_TO_TILES                   = VR_CINSTR_COUNTER_SOURCE_GP + 15,
	VR_CINSTR_GP_NUMBER_OF_MEMORY_BLOCKS_ALLOCATED                     = VR_CINSTR_COUNTER_SOURCE_GP + 16,
	VR_CINSTR_GP_RESERVED_17                                           = VR_CINSTR_COUNTER_SOURCE_GP + 17,
	VR_CINSTR_GP_RESERVED_18                                           = VR_CINSTR_COUNTER_SOURCE_GP + 18,
	VR_CINSTR_GP_NUMBER_OF_VERTEX_LOADER_CACHE_MISSES                  = VR_CINSTR_COUNTER_SOURCE_GP + 19,
	VR_CINSTR_GP_RESERVED_20                                           = VR_CINSTR_COUNTER_SOURCE_GP + 20,
	VR_CINSTR_GP_RESERVED_21                                           = VR_CINSTR_COUNTER_SOURCE_GP + 21,
	VR_CINSTR_GP_ACTIVE_CYCLES_VERTEX_SHADER_COMMAND_PROCESSOR         = VR_CINSTR_COUNTER_SOURCE_GP + 22,
	VR_CINSTR_GP_ACTIVE_CYCLES_PLBU_COMMAND_PROCESSOR                  = VR_CINSTR_COUNTER_SOURCE_GP + 23,
	VR_CINSTR_GP_ACTIVE_CYCLES_PLBU_LIST_WRITER                        = VR_CINSTR_COUNTER_SOURCE_GP + 24,
	VR_CINSTR_GP_ACTIVE_CYCLES_THROUGH_THE_PREPARE_LIST_COMMANDS       = VR_CINSTR_COUNTER_SOURCE_GP + 25,
	VR_CINSTR_GP_RESERVED_26                                           = VR_CINSTR_COUNTER_SOURCE_GP + 26,
	VR_CINSTR_GP_ACTIVE_CYCLES_PRIMITIVE_ASSEMBLY                      = VR_CINSTR_COUNTER_SOURCE_GP + 27,
	VR_CINSTR_GP_ACTIVE_CYCLES_PLBU_VERTEX_FETCHER                     = VR_CINSTR_COUNTER_SOURCE_GP + 28,
	VR_CINSTR_GP_RESERVED_29                                           = VR_CINSTR_COUNTER_SOURCE_GP + 29,
	VR_CINSTR_GP_ACTIVE_CYCLES_BOUNDINGBOX_AND_COMMAND_GENERATOR       = VR_CINSTR_COUNTER_SOURCE_GP + 30,
	VR_CINSTR_GP_RESERVED_31                                           = VR_CINSTR_COUNTER_SOURCE_GP + 31,
	VR_CINSTR_GP_ACTIVE_CYCLES_SCISSOR_TILE_ITERATOR                   = VR_CINSTR_COUNTER_SOURCE_GP + 32,
	VR_CINSTR_GP_ACTIVE_CYCLES_PLBU_TILE_ITERATOR                      = VR_CINSTR_COUNTER_SOURCE_GP + 33,
	VR_CINSTR_GP_JOB_COUNT                                             = VR_CINSTR_COUNTER_SOURCE_GP + 900,

	/* Vr PP counters */

	VR_CINSTR_PP_ACTIVE_CLOCK_CYCLES_COUNT                             = VR_CINSTR_COUNTER_SOURCE_PP + 0,
	VR_CINSTR_PP_TOTAL_CLOCK_CYCLES_COUNT_REMOVED                      = VR_CINSTR_COUNTER_SOURCE_PP + 1,
	VR_CINSTR_PP_TOTAL_BUS_READS                                       = VR_CINSTR_COUNTER_SOURCE_PP + 2,
	VR_CINSTR_PP_TOTAL_BUS_WRITES                                      = VR_CINSTR_COUNTER_SOURCE_PP + 3,
	VR_CINSTR_PP_BUS_READ_REQUEST_CYCLES_COUNT                         = VR_CINSTR_COUNTER_SOURCE_PP + 4,
	VR_CINSTR_PP_BUS_WRITE_REQUEST_CYCLES_COUNT                        = VR_CINSTR_COUNTER_SOURCE_PP + 5,
	VR_CINSTR_PP_BUS_READ_TRANSACTIONS_COUNT                           = VR_CINSTR_COUNTER_SOURCE_PP + 6,
	VR_CINSTR_PP_BUS_WRITE_TRANSACTIONS_COUNT                          = VR_CINSTR_COUNTER_SOURCE_PP + 7,
	VR_CINSTR_PP_RESERVED_08                                           = VR_CINSTR_COUNTER_SOURCE_PP + 8,
	VR_CINSTR_PP_TILE_WRITEBACK_WRITES                                 = VR_CINSTR_COUNTER_SOURCE_PP + 9,
	VR_CINSTR_PP_STORE_UNIT_WRITES                                     = VR_CINSTR_COUNTER_SOURCE_PP + 10,
	VR_CINSTR_PP_RESERVED_11                                           = VR_CINSTR_COUNTER_SOURCE_PP + 11,
	VR_CINSTR_PP_PALETTE_CACHE_READS                                   = VR_CINSTR_COUNTER_SOURCE_PP + 12,
	VR_CINSTR_PP_TEXTURE_CACHE_UNCOMPRESSED_READS                      = VR_CINSTR_COUNTER_SOURCE_PP + 13,
	VR_CINSTR_PP_POLYGON_LIST_READS                                    = VR_CINSTR_COUNTER_SOURCE_PP + 14,
	VR_CINSTR_PP_RSW_READS                                             = VR_CINSTR_COUNTER_SOURCE_PP + 15,
	VR_CINSTR_PP_VERTEX_CACHE_READS                                    = VR_CINSTR_COUNTER_SOURCE_PP + 16,
	VR_CINSTR_PP_UNIFORM_REMAPPING_READS                               = VR_CINSTR_COUNTER_SOURCE_PP + 17,
	VR_CINSTR_PP_PROGRAM_CACHE_READS                                   = VR_CINSTR_COUNTER_SOURCE_PP + 18,
	VR_CINSTR_PP_VARYING_READS                                         = VR_CINSTR_COUNTER_SOURCE_PP + 19,
	VR_CINSTR_PP_TEXTURE_DESCRIPTORS_READS                             = VR_CINSTR_COUNTER_SOURCE_PP + 20,
	VR_CINSTR_PP_TEXTURE_DESCRIPTORS_REMAPPING_READS                   = VR_CINSTR_COUNTER_SOURCE_PP + 21,
	VR_CINSTR_PP_TEXTURE_CACHE_COMPRESSED_READS                        = VR_CINSTR_COUNTER_SOURCE_PP + 22,
	VR_CINSTR_PP_LOAD_UNIT_READS                                       = VR_CINSTR_COUNTER_SOURCE_PP + 23,
	VR_CINSTR_PP_POLYGON_COUNT                                         = VR_CINSTR_COUNTER_SOURCE_PP + 24,
	VR_CINSTR_PP_PIXEL_RECTANGLE_COUNT                                 = VR_CINSTR_COUNTER_SOURCE_PP + 25,
	VR_CINSTR_PP_LINES_COUNT                                           = VR_CINSTR_COUNTER_SOURCE_PP + 26,
	VR_CINSTR_PP_POINTS_COUNT                                          = VR_CINSTR_COUNTER_SOURCE_PP + 27,
	VR_CINSTR_PP_STALL_CYCLES_POLYGON_LIST_READER                      = VR_CINSTR_COUNTER_SOURCE_PP + 28,
	VR_CINSTR_PP_STALL_CYCLES_TRIANGLE_SETUP                           = VR_CINSTR_COUNTER_SOURCE_PP + 29,
	VR_CINSTR_PP_QUAD_RASTERIZED_COUNT                                 = VR_CINSTR_COUNTER_SOURCE_PP + 30,
	VR_CINSTR_PP_FRAGMENT_RASTERIZED_COUNT                             = VR_CINSTR_COUNTER_SOURCE_PP + 31,
	VR_CINSTR_PP_FRAGMENT_REJECTED_FRAGMENT_KILL_COUNT                 = VR_CINSTR_COUNTER_SOURCE_PP + 32,
	VR_CINSTR_PP_FRAGMENT_REJECTED_FWD_FRAGMENT_KILL_COUNT             = VR_CINSTR_COUNTER_SOURCE_PP + 33,
	VR_CINSTR_PP_FRAGMENT_PASSED_ZSTENCIL_COUNT                        = VR_CINSTR_COUNTER_SOURCE_PP + 34,
	VR_CINSTR_PP_PATCHES_REJECTED_EARLY_Z_STENCIL_COUNT                = VR_CINSTR_COUNTER_SOURCE_PP + 35,
	VR_CINSTR_PP_PATCHES_EVALUATED                                     = VR_CINSTR_COUNTER_SOURCE_PP + 36,
	VR_CINSTR_PP_INSTRUCTION_COMPLETED_COUNT                           = VR_CINSTR_COUNTER_SOURCE_PP + 37,
	VR_CINSTR_PP_INSTRUCTION_FAILED_RENDEZVOUS_COUNT                   = VR_CINSTR_COUNTER_SOURCE_PP + 38,
	VR_CINSTR_PP_INSTRUCTION_FAILED_VARYING_MISS_COUNT                 = VR_CINSTR_COUNTER_SOURCE_PP + 39,
	VR_CINSTR_PP_INSTRUCTION_FAILED_TEXTURE_MISS_COUNT                 = VR_CINSTR_COUNTER_SOURCE_PP + 40,
	VR_CINSTR_PP_INSTRUCTION_FAILED_LOAD_MISS_COUNT                    = VR_CINSTR_COUNTER_SOURCE_PP + 41,
	VR_CINSTR_PP_INSTRUCTION_FAILED_TILE_READ_MISS_COUNT               = VR_CINSTR_COUNTER_SOURCE_PP + 42,
	VR_CINSTR_PP_INSTRUCTION_FAILED_STORE_MISS_COUNT                   = VR_CINSTR_COUNTER_SOURCE_PP + 43,
	VR_CINSTR_PP_RENDEZVOUS_BREAKAGE_COUNT                             = VR_CINSTR_COUNTER_SOURCE_PP + 44,
	VR_CINSTR_PP_PIPELINE_BUBBLES_CYCLE_COUNT                          = VR_CINSTR_COUNTER_SOURCE_PP + 45,
	VR_CINSTR_PP_TEXTURE_MAPPER_MULTIPASS_COUNT                        = VR_CINSTR_COUNTER_SOURCE_PP + 46,
	VR_CINSTR_PP_TEXTURE_MAPPER_CYCLE_COUNT                            = VR_CINSTR_COUNTER_SOURCE_PP + 47,
	VR_CINSTR_PP_VERTEX_CACHE_HIT_COUNT                                = VR_CINSTR_COUNTER_SOURCE_PP + 48,
	VR_CINSTR_PP_VERTEX_CACHE_MISS_COUNT                               = VR_CINSTR_COUNTER_SOURCE_PP + 49,
	VR_CINSTR_PP_VARYING_CACHE_HIT_COUNT                               = VR_CINSTR_COUNTER_SOURCE_PP + 50,
	VR_CINSTR_PP_VARYING_CACHE_MISS_COUNT                              = VR_CINSTR_COUNTER_SOURCE_PP + 51,
	VR_CINSTR_PP_VARYING_CACHE_CONFLICT_MISS_COUNT                     = VR_CINSTR_COUNTER_SOURCE_PP + 52,
	VR_CINSTR_PP_TEXTURE_CACHE_HIT_COUNT                               = VR_CINSTR_COUNTER_SOURCE_PP + 53,
	VR_CINSTR_PP_TEXTURE_CACHE_MISS_COUNT                              = VR_CINSTR_COUNTER_SOURCE_PP + 54,
	VR_CINSTR_PP_TEXTURE_CACHE_CONFLICT_MISS_COUNT                     = VR_CINSTR_COUNTER_SOURCE_PP + 55,
	VR_CINSTR_PP_PALETTE_CACHE_HIT_COUNT                               = VR_CINSTR_COUNTER_SOURCE_PP + 56, /* Vr 200 only */
	VR_CINSTR_PP_PALETTE_CACHE_MISS_COUNT                              = VR_CINSTR_COUNTER_SOURCE_PP + 57, /* Vr 200 only */
	VR_CINSTR_PP_COMPRESSED_TEXTURE_CACHE_HIT_COUNT                    = VR_CINSTR_COUNTER_SOURCE_PP + 56, /* Vr 400 class only */
	VR_CINSTR_PP_COMPRESSED_TEXTURE_CACHE_MISS_COUNT                   = VR_CINSTR_COUNTER_SOURCE_PP + 57, /* Vr 400 class only */
	VR_CINSTR_PP_LOAD_STORE_CACHE_HIT_COUNT                            = VR_CINSTR_COUNTER_SOURCE_PP + 58,
	VR_CINSTR_PP_LOAD_STORE_CACHE_MISS_COUNT                           = VR_CINSTR_COUNTER_SOURCE_PP + 59,
	VR_CINSTR_PP_PROGRAM_CACHE_HIT_COUNT                               = VR_CINSTR_COUNTER_SOURCE_PP + 60,
	VR_CINSTR_PP_PROGRAM_CACHE_MISS_COUNT                              = VR_CINSTR_COUNTER_SOURCE_PP + 61,
	VR_CINSTR_PP_JOB_COUNT                                             = VR_CINSTR_COUNTER_SOURCE_PP + 900,
} cinstr_counters_m200_t;

#endif /*_VR_UTGARD_COUNTERS_H_*/
