#
# Copyright 2009 Nexell Co.
#
# Makefile for the S5P4418

obj-y					:= board.o device.o nanopi-lcds.o touch.o wifi_pm.o bt_bcm.o
obj-$(CONFIG_SUSPEND)			+= pm.o
obj-$(CONFIG_ION_NXP)			+= dev-ion.o
obj-$(CONFIG_USB_CONNECT_NXP_DRV)	+= usb-connector.o

