obj-$(CONFIG_NXP_M2M_SCALER) += nxp-scaler.o
obj-$(CONFIG_NXP_M2M_DEINTERLACER) += nxp-deinterlacer.o

EXTRA_CFLAGS += -I$(srctree)/arch/arm/mach-s5p4418/prototype/base -I$(srctree)/arch/arm/mach-s5p4418/prototype/module
