obj-$(CONFIG_KP_AXP22) += axp-mfd.o

#Make this built-in, so that it will be loaded before I2C driver

obj-$(CONFIG_KP_AXP22) += axp22-board.o
obj-$(CONFIG_KP_AXP22) += axp22-regu.o
obj-$(CONFIG_KP_AXP22) += axp22-sply.o
obj-$(CONFIG_AXP_GPIO) += axp22-gpio.o
#obj-$(CONFIG_KP_AXP22) += virtual22.o
#obj-$(CONFIG_KP_AXP22) += virtual22_dev.o
