#ifndef __S5P6818_BUS_HEADER__
#define __S5P6818_BUS_HEADER__


#define NX_DREX_QOS_OFFSET          (0x60)

#define NX_PA_BASE_REG_DREX         (0xC00E0000)
#define NX_PA_BASE_REG_DDRPHY       (0xC00E1000)

#define NX_VA_BASE_REG_DREX         IO_ADDRESS(NX_PA_BASE_REG_DREX)
#define NX_VA_BASE_REG_DDRPHY       IO_ADDRESS(NX_PA_BASE_REG_DDRPHY)


#define NX_PL301_QOS_TRDMARK_OFFSET     (0x400)
#define NX_PL301_QOS_CTRL_OFFSET        (0x404)
#define NX_PL301_AR_OFFSET              (0x408)
#define NX_PL301_AW_OFFSET              (0x40C)

#define NX_PA_BASE_REG_PL301_DISP   (0xC005E000)
#define NX_PA_BASE_REG_PL301_BOTT   (0xC0050000)
#define NX_PA_BASE_REG_PL301_TOP    (0xC0052000)

#define NX_VA_BASE_REG_PL301_DISP   IO_ADDRESS(NX_PA_BASE_REG_PL301_DISP)
#define NX_VA_BASE_REG_PL301_BOTT   IO_ADDRESS(NX_PA_BASE_REG_PL301_BOTT)
#define NX_VA_BASE_REG_PL301_TOP    IO_ADDRESS(NX_PA_BASE_REG_PL301_TOP)

#define NX_BASE_REG_PL301_DISP_QOS_TRDMARK  (NX_VA_BASE_REG_PL301_DISP | NX_PL301_QOS_TRDMARK_OFFSET)
#define NX_BASE_REG_PL301_DISP_QOS_CTRL     (NX_VA_BASE_REG_PL301_DISP | NX_PL301_QOS_CTRL_OFFSET)
#define NX_BASE_REG_PL301_DISP_AR           (NX_VA_BASE_REG_PL301_DISP | NX_PL301_AR_OFFSET)
#define NX_BASE_REG_PL301_DISP_AW           (NX_VA_BASE_REG_PL301_DISP | NX_PL301_AW_OFFSET)

#define NX_BASE_REG_PL301_BOTT_QOS_TRDMARK  (NX_VA_BASE_REG_PL301_BOTT | NX_PL301_QOS_TRDMARK_OFFSET)
#define NX_BASE_REG_PL301_BOTT_QOS_CTRL     (NX_VA_BASE_REG_PL301_BOTT | NX_PL301_QOS_CTRL_OFFSET)
#define NX_BASE_REG_PL301_BOTT_AR           (NX_VA_BASE_REG_PL301_BOTT | NX_PL301_AR_OFFSET)
#define NX_BASE_REG_PL301_BOTT_AW           (NX_VA_BASE_REG_PL301_BOTT | NX_PL301_AW_OFFSET)

#define NX_BASE_REG_PL301_TOP_QOS_TRDMARK   (NX_VA_BASE_REG_PL301_TOP | NX_PL301_QOS_TRDMARK_OFFSET)
#define NX_BASE_REG_PL301_TOP_QOS_CTRL      (NX_VA_BASE_REG_PL301_TOP | NX_PL301_QOS_CTRL_OFFSET)
#define NX_BASE_REG_PL301_TOP_AR            (NX_VA_BASE_REG_PL301_TOP | NX_PL301_AR_OFFSET)
#define NX_BASE_REG_PL301_TOP_AW            (NX_VA_BASE_REG_PL301_TOP | NX_PL301_AW_OFFSET)

#define SI_IF_NUM_POS   0
#define SLOT_NUM_POS    24

// Interface slot number of  TOP_BUS.
#define TOPBUS_SI_SLOT_DMAC0        0
#define TOPBUS_SI_SLOT_MP2TS        1
#define TOPBUS_SI_SLOT_DMAC1        2
#define TOPBUS_SI_SLOT_REMAP        3
#define TOPBUS_SI_SLOT_SDMMC        4
#define TOPBUS_SI_SLOT_USBOTG       5
#define TOPBUS_SI_SLOT_USBHOST0     6
#define TOPBUS_SI_SLOT_USBHOST1     7

// Interface slot number of  BOTTOM_BUS.
#define BOTBUS_SI_SLOT_1ST_ARM      0
#define BOTBUS_SI_SLOT_2ND_ARM      1
#define BOTBUS_SI_SLOT_MALI         2
#define BOTBUS_SI_SLOT_TOP          3
#define BOTBUS_SI_SLOT_DEINTERLACE  4
#define BOTBUS_SI_SLOT_1ST_CODA     5
#define BOTBUS_SI_SLOT_2ND_CODA     6
#define BOTBUS_SI_SLOT_SCALER       7

// Interface slot number of  DISPLAY_BUS.
#define DISBUS_SI_SLOT_1ST_DISPLAY  0
#define DISBUS_SI_SLOT_2ND_DISPLAY  1
#define DISBUS_SI_SLOT_GMAC         2

/*------------------------------------------------------------------------------*/

extern const u16    g_DrexQoS[];
extern const u8     g_TopBusSI[];
extern const u8     g_BottomBusSI[];
extern const u8     g_DispBusSI[];
extern const u8     g_BottomQoSSI[];


#endif  //__S5P6818_BUS_HEADER__

