#
# Makefile for industrial I/O Light sensors
#

obj-$(CONFIG_SENSORS_BH1721)	+= bh1721fvc.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_TSL2583)	+= tsl2583.o
