#
# Copyright 2009 Nexell Co.
#
# Makefile for the SLsi CPU

obj-y += peri_reset.o gpio.o

obj-$(CONFIG_NXP_PWM)		+= pwm.o
obj-$(CONFIG_NXP_DISPLAY)		+= display.o
obj-$(CONFIG_NXP_DISPLAY_LCD)	+= display_lcd.o
obj-$(CONFIG_NXP_DISPLAY_LVDS)	+= display_lvds.o
obj-$(CONFIG_NXP_DISPLAY_HDMI)	+= display_hdmi.o hdmi/
obj-$(CONFIG_NXP_DISPLAY_MIPI)	+= display_mipi.o
obj-$(CONFIG_NXP_DISPLAY_RESC)	+= display_resc.o
obj-$(CONFIG_USB_EHCI_SYNOPSYS)	+= setup-usb-phy.o
obj-$(CONFIG_NXP_OUT_HDMI)		+= hdmi/

